name: Deploy to Firebaseon merge
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy to Firebase on merge
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
      - env:
          API_KEY: ${{ secrets.API_KEY }}
          APP_ID: ${{ secrets.APP_ID }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ATHENA_4F232 }}"
          channelId: live
          projectId: athena-4f232
