name: Vulnerability-Check
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Vulnerability-Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL, HIGH, MEDIUM"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
#       - name: Send mail
#         uses: dawidd6/action-send-mail@v3
#         with:
#           # Required mail server address:
#           server_address: securesmtp.t-online.de
#           # Required mail server port:
#           server_port: 465
#           username: ${{secrets.MAIL_USERNAME}}
#           password: ${{secrets.MAIL_PASSWORD}}
#           subject: Test Trivy
#           # Required recipients' addresses:
#           to: ${{secrets.NOTIFY_MAIL}}
#           # Required sender full name (address can be skipped):
#           from: GitHub Action Trivy # <user@example.com>
#           # Optional whether this connection use TLS (default is true if server_port is 465)
# #           secure: true
#           # Optional plain body:
#           body: Build job of completed successfully!
#           attachments: trivy-results.sarif

